// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCww27s1R3e_ryDN-1dhg3mihUfdocAOtg',
    appId: '1:503800159046:web:c4d02ada7e7d7a573ba347',
    messagingSenderId: '503800159046',
    projectId: 'kuliah-2b2c',
    authDomain: 'kuliah-2b2c.firebaseapp.com',
    storageBucket: 'kuliah-2b2c.firebasestorage.app',
    measurementId: 'G-6R1TKGGKTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9J8fyGoqnSmd0-Bs1yVtasArYp2f2sY0',
    appId: '1:503800159046:android:3fa388d1c5a84d8b3ba347',
    messagingSenderId: '503800159046',
    projectId: 'kuliah-2b2c',
    storageBucket: 'kuliah-2b2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARlcBdS5XF4Y-OP12XHsJvI_i0sUD8xt4',
    appId: '1:503800159046:ios:15d0b517899cbc923ba347',
    messagingSenderId: '503800159046',
    projectId: 'kuliah-2b2c',
    storageBucket: 'kuliah-2b2c.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARlcBdS5XF4Y-OP12XHsJvI_i0sUD8xt4',
    appId: '1:503800159046:ios:15d0b517899cbc923ba347',
    messagingSenderId: '503800159046',
    projectId: 'kuliah-2b2c',
    storageBucket: 'kuliah-2b2c.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCww27s1R3e_ryDN-1dhg3mihUfdocAOtg',
    appId: '1:503800159046:web:ba9914e61b4ca2333ba347',
    messagingSenderId: '503800159046',
    projectId: 'kuliah-2b2c',
    authDomain: 'kuliah-2b2c.firebaseapp.com',
    storageBucket: 'kuliah-2b2c.firebasestorage.app',
    measurementId: 'G-Q3TE3T0XHT',
  );
}
